Dirty hierarchy
TRIPP-Inc/com.tripp.leximperialis pull request #11
Opened 2024-11-12 23:00 UTC by Gabo-7

# {Replace with Ticket #}
- [ ] Updated Version
- [ ] Updated Change Log
# Description
Please write a brief description of the work that you did and what you're aiming to accomplish.
# Testing
Please create a checklist of what to test for.
- [ ] Check list shows boxes.
- [ ] Hyperlink for ticket works.
- [ ] etc.

2024-11-14 00:04 UTC, mbracks commented
Lex Imperialis finds Flipped UVs and Overlapping UVs on clean Pheonix
- :white_check_mark: UV infraction
![image](https://github.com/user-attachments/assets/f4f01ff4-a776-420a-9900-b632babfa74b)

2024-11-14 01:08 UTC, mbracks commented
- :white_check_mark: Dirty Hierarchy check finds empty game objects
- :x: Dirty transforms doesn't find dirty transforms on objects that were exported as a group

2024-11-19 00:11 UTC, mbracks requested changes

2024-11-19 00:11 UTC, mbracks commented on Packages/com.tripp.leximperialis/Editor/ModelJudicator.cs
> +                    result.Add(new Infraction
You need an if statement to check the results of the bools above before adding a new infraction.

2024-11-19 00:11 UTC, mbracks commented on Packages/com.tripp.leximperialis/Editor/ModelJudicator.cs
> +            else if(rootObject.GetComponents<Component>().Count() == 1)
In this scenario, the root object isn't checked for dirty transforms only it's children.

2024-11-19 00:11 UTC, mbracks commented on Packages/com.tripp.leximperialis/Editor/ModelJudicator.cs
> +            List<Infraction> result = new List<Infraction>();
Initializing the list early.

2024-11-19 00:11 UTC, mbracks commented on Packages/com.tripp.leximperialis/Editor/ModelJudicator.cs
> +            List<Mesh> subMeshes = new List<Mesh>();
Early initialization of a list.

2024-11-20 21:23 UTC, Gabo-7 commented on Packages/com.tripp.leximperialis/Editor/ModelJudicator.cs
> +            List<Infraction> result = new List<Infraction>();
The initialization is necessary. Not initializing, or using null, makes it break; compile error and runtime error respectively.

2024-11-20 23:39 UTC, Gabo-7 commented on Packages/com.tripp.leximperialis/Editor/ModelJudicator.cs
> +                    result.Add(new Infraction
Added a check, but some things are still unclear

2024-11-21 20:14 UTC, mbracks requested changes

2024-11-21 20:15 UTC, mbracks approved these changes
Great work

2024-11-21 20:15 UTC, merged